default_group_behavior:
  enabled: false
  archive: false
  speak: false
  proactive_reply: true
  proactive_interval_seconds: "180-480"
  image_generation: true

groups:
  "515267906":
    enabled: true
    archive: true
    speak: true
    proactive_reply: true
    proactive_interval_seconds: "180-480"
    image_generation: true
    long_context_history: false

  "300520120":
    enabled: true
    archive: false
    speak: true
    proactive_reply: false
    proactive_interval_seconds: "180-480"
    image_generation: false
